import { mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { globalConfigDir } from "./config.ts";

export type CompletionShell = "bash" | "fish" | "powershell" | "zsh";

const COMPLETION_SHELLS: readonly CompletionShell[] = [
  "bash",
  "fish",
  "powershell",
  "zsh",
];
const COMPLETION_BLOCK_PATTERN = /# chump completion\n[\s\S]*?# \/chump completion\n?/u;

export function parseCompletionShell(value: string | undefined): CompletionShell {
  if (value === "bash" || value === "fish" || value === "powershell" || value === "zsh") {
    return value;
  }
  throw new Error(
    `unknown completion shell: ${value ?? ""}. Expected one of: ${COMPLETION_SHELLS.join(", ")}`,
  );
}

export function completionCommandUsage(): string {
  return "chump completion <bash|fish|powershell|zsh>";
}

export function renderShellCompletion(shell: CompletionShell): string {
  if (shell === "bash") return bashCompletion();
  if (shell === "fish") return fishCompletion();
  if (shell === "powershell") return powershellCompletion();
  return zshCompletion();
}

/**
 * Makes a global npm installation work like the platform installers: the
 * first interactive launch writes a static script and sources it from the
 * user's current shell profile. Source checkouts are deliberately excluded so
 * development commands never edit a contributor's shell configuration.
 */
export async function enablePackageShellCompletion(): Promise<void> {
  if (!isInstalledPackage() || process.platform === "win32") {
    return;
  }

  const target = completionProfileTarget();
  if (!target) {
    return;
  }

  const completionsDirectory = path.join(globalConfigDir(), "completions");
  const scriptPath = path.join(completionsDirectory, `chump.${target.shell}`);
  const sourceBlock = [
    "# chump completion",
    `source \"${shellDoubleQuote(scriptPath)}\"`,
    "# /chump completion",
    "",
  ].join("\n");

  try {
    await mkdir(completionsDirectory, { recursive: true, mode: 0o700 });
    await writeFile(scriptPath, renderShellCompletion(target.shell), "utf8");
    await mkdir(path.dirname(target.profilePath), { recursive: true, mode: 0o700 });

    const profile = await readFile(target.profilePath, "utf8").catch(
      (error: unknown) => isMissingFile(error) ? "" : Promise.reject(error),
    );
    const nextProfile = profile.includes("# chump completion")
      ? profile.replace(COMPLETION_BLOCK_PATTERN, sourceBlock)
      : `${profile}${profile.endsWith("\n") || profile.length === 0 ? "" : "\n"}${sourceBlock}`;
    if (nextProfile !== profile) {
      await writeFile(
        target.profilePath,
        nextProfile,
        "utf8",
      );
    }
  } catch {
    // Completion must never prevent a normal CLI invocation. The platform
    // installer remains responsible for reporting write failures explicitly.
  }
}

function completionProfileTarget(): { shell: Exclude<CompletionShell, "powershell">; profilePath: string } | null {
  const shell = path.basename(process.env.SHELL ?? "");
  const home = os.homedir();
  if (shell === "bash") {
    return { shell, profilePath: path.join(home, ".bashrc") };
  }
  if (shell === "zsh") {
    return {
      shell,
      profilePath: path.join(process.env.ZDOTDIR ?? home, ".zshrc"),
    };
  }
  if (shell === "fish") {
    return {
      shell,
      profilePath: path.join(process.env.XDG_CONFIG_HOME ?? path.join(home, ".config"), "fish", "config.fish"),
    };
  }
  return null;
}

function isInstalledPackage(): boolean {
  return import.meta.url.includes("/node_modules/chump-agent/");
}

function isMissingFile(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === "object" && error !== null &&
    "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT";
}

function shellDoubleQuote(value: string): string {
  return value.replaceAll(/[$`"\\]/gu, "\\$&");
}

function bashCompletion(): string {
  return `# shellcheck shell=bash
# Generated by chump. This file does not invoke chump while completing.
_chump_completion() {
  local cur prev cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cword="$COMP_CWORD"

  local commands="app client completion connect daemon projects providers server status stop update version"
  local global_options="-h --help -v --version -c --connect -s --session -p --print --verbose -m --model -t --thinking"

  case "\${COMP_WORDS[1]}" in
    daemon)
      if (( cword == 2 )); then
        COMPREPLY=( $(compgen -W "start status stop" -- "$cur") )
      fi
      return
      ;;
    projects)
      if (( cword == 2 )); then
        COMPREPLY=( $(compgen -W "list add remove" -- "$cur") )
        return
      fi
      case "\${COMP_WORDS[2]}" in
        add)
          if [[ "$prev" == "--name" ]]; then
            return
          fi
          COMPREPLY=( $(compgen -W "--name" -- "$cur") )
          compopt -o filenames
          return
          ;;
        remove)
          return
          ;;
      esac
      ;;
    app)
      COMPREPLY=( $(compgen -W "--web-url --no-open --json" -- "$cur") )
      return
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash fish powershell zsh" -- "$cur") )
      return
      ;;
  esac

  case "$prev" in
    -t|--thinking)
      COMPREPLY=( $(compgen -W "none low high xhigh" -- "$cur") )
      return
      ;;
    -c|--connect|--web-url|-s|--session|-m|--model)
      return
      ;;
  esac

  COMPREPLY=( $(compgen -W "$commands $global_options" -- "$cur") )
}
complete -F _chump_completion chump
`;
}

function fishCompletion(): string {
  return `# Generated by chump. This file does not invoke chump while completing.
complete -c chump -f

complete -c chump -n '__fish_use_subcommand' -a app -d 'Open the Chump web app'
complete -c chump -n '__fish_use_subcommand' -a client -d 'Start the CLI without auto-starting a server'
complete -c chump -n '__fish_use_subcommand' -a completion -d 'Print shell completion'
complete -c chump -n '__fish_use_subcommand' -a connect -d 'Connect a provider'
complete -c chump -n '__fish_use_subcommand' -a daemon -d 'Manage the local coordinator'
complete -c chump -n '__fish_use_subcommand' -a projects -d 'Manage registered projects'
complete -c chump -n '__fish_use_subcommand' -a providers -d 'List providers'
complete -c chump -n '__fish_use_subcommand' -a server -d 'Run the backend in the foreground'
complete -c chump -n '__fish_use_subcommand' -a status -d 'Show server health'
complete -c chump -n '__fish_use_subcommand' -a stop -d 'Stop the managed server'
complete -c chump -n '__fish_use_subcommand' -a update -d 'Update Chump'
complete -c chump -n '__fish_use_subcommand' -a version -d 'Print the version'

complete -c chump -s h -l help -d 'Show help'
complete -c chump -s v -l version -d 'Print the version'
complete -c chump -s c -l connect -r -d 'Connect to a server URL'
complete -c chump -s s -l session -r -d 'Resume a session'
complete -c chump -s p -l print -d 'Run one prompt without the TUI'
complete -c chump -l verbose -d 'Show diagnostics with --print'
complete -c chump -s m -l model -r -d 'Select a model with --print'
complete -c chump -s t -l thinking -r -a 'none low high xhigh' -d 'Set thinking level with --print'

complete -c chump -n '__fish_seen_subcommand_from daemon' -a 'start status stop'
complete -c chump -n '__fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from list add remove' -a 'list add remove'
complete -c chump -n '__fish_seen_subcommand_from projects; and __fish_seen_subcommand_from add' -l name -r -d 'Project name'
complete -c chump -n '__fish_seen_subcommand_from app' -l web-url -r -d 'Web app URL'
complete -c chump -n '__fish_seen_subcommand_from app' -l no-open -d 'Do not open a browser'
complete -c chump -n '__fish_seen_subcommand_from app' -l json -d 'Print JSON only'
complete -c chump -n '__fish_seen_subcommand_from completion' -a 'bash fish powershell zsh'
`;
}

function powershellCompletion(): string {
  return `# Generated by chump. This file does not invoke chump while completing.
Register-ArgumentCompleter -Native -CommandName chump -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
    $command = if ($words.Count -gt 1) { $words[1] } else { $null }
    $candidates = switch ($command) {
        'daemon' { @('start', 'status', 'stop') }
        'projects' {
            if ($words.Count -le 2) { @('list', 'add', 'remove') }
            elseif ($words[2] -eq 'add') { @('--name') }
            else { @() }
        }
        'app' { @('--web-url', '--no-open', '--json') }
        'completion' { @('bash', 'fish', 'powershell', 'zsh') }
        default {
            @(
                'app', 'client', 'completion', 'connect', 'daemon', 'projects', 'providers',
                'server', 'status', 'stop', 'update', 'version',
                '-h', '--help', '-v', '--version', '-c', '--connect', '-s', '--session',
                '-p', '--print', '--verbose', '-m', '--model', '-t', '--thinking'
            )
        }
    }

    if ($words.Count -gt 1 -and $words[$words.Count - 2] -in @('-t', '--thinking')) {
        $candidates = @('none', 'low', 'high', 'xhigh')
    }

    $candidates |
        Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
`;
}

function zshCompletion(): string {
  return `#compdef chump
# Generated by chump. This file does not invoke chump while completing.

_chump() {
  local -a commands global_options
  commands=(
    'app:open the Chump web app'
    'client:start the CLI without auto-starting a server'
    'completion:print shell completion'
    'connect:connect a provider'
    'daemon:manage the local coordinator'
    'projects:manage registered projects'
    'providers:list providers'
    'server:run the backend in the foreground'
    'status:show server health'
    'stop:stop the managed server'
    'update:update Chump'
    'version:print the version'
  )
  global_options=(
    '(-h --help)'{-h,--help}'[show help]'
    '(-v --version)'{-v,--version}'[print the version]'
    '(-c --connect)'{-c,--connect}'[connect to a server URL]:server URL'
    '(-s --session)'{-s,--session}'[resume a session]:session ID'
    '(-p --print)'{-p,--print}'[run one prompt without the TUI]'
    '--verbose[show diagnostics with --print]'
    '(-m --model)'{-m,--model}'[select a model with --print]:provider/model'
    '(-t --thinking)'{-t,--thinking}'[set thinking level with --print]:(none low high xhigh)'
  )

  if (( CURRENT == 2 )); then
    _describe -t commands command "$commands"
    _describe -t options option "$global_options"
    return
  fi

  case "$words[2]" in
    daemon)
      _values 'daemon command' start status stop
      ;;
    projects)
      if (( CURRENT == 3 )); then
        _values 'projects command' list add remove
      elif [[ "$words[3]" == add ]]; then
        _arguments '--name[project name]:name' '*:workspace directory:_files -/'
      fi
      ;;
    app)
      _arguments '--web-url[web app URL]:URL' '--no-open[do not open a browser]' '--json[print JSON only]'
      ;;
    completion)
      _values 'shell' bash fish powershell zsh
      ;;
    *)
      _arguments -S "\${global_options[@]}"
      ;;
  esac
}

compdef _chump chump
`;
}
